export const sample_foods = [
  {
    id: '1',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Cheese Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'food-2.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '3',
    name: 'Hamburger',
    cookTime: '10-20',
    price: 8,
    favorite: true,
    origins: ['germany', 'usa'],
    stars: 4.5,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Hamburger', 'Lunch'],
  },
  {
    id: '4',
    name: 'Fries',
    cookTime: '10-20',
    price: 3,
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 4.5,
    imageUrl: 'food-4.jpg',
    tags: ['FastFood', 'Fries', 'Lunch'],
  },
  {
    id: '5',
    name: 'Chefs Sandwhich',
    cookTime: '10-20',
    price: 3,
    favorite: true,
    origins: ['world', 'usa'],
    stars: 4.5,
    imageUrl: 'food-5.jpg',
    tags: ['FastFood', 'Sandwhich', 'Lunch'],
  },
]